Repository fjelltopp/ckanext-zarr, pull requests merged in 2024-10, with the labels that each got.

#32 173 Custom Fields when modifying organisation
  ckanext/zarr/templates/organization/snippets/organization_form.html
Labels: patch

#41 Add Zambia flag colors on promoted
  ckanext/zarr/assets/css/zarr.css
  ckanext/zarr/assets/css/zarr_palette.css
  ckanext/zarr/templates/admin/base.html
  ckanext/zarr/templates/group/edit_base.html
  ckanext/zarr/templates/group/read_base.html
  ckanext/zarr/templates/header.html
  ckanext/zarr/templates/home/layout1.html
  ckanext/zarr/templates/organization/edit_base.html
  ckanext/zarr/templates/organization/read_base.html
  ckanext/zarr/templates/package/base.html
  ckanext/zarr/templates/page.html
  ckanext/zarr/templates/user/edit_base.html
  ckanext/zarr/templates/user/read_base.html
Labels: enhancement, minor

#42 179 - Change name
  README.md
  ckanext/zarr/templates/header.html
  ckanext/zarr/templates/home/snippets/about_text.html
  ckanext/zarr/templates/home/snippets/insights.html
  ckanext/zarr/templates/home/snippets/promoted.html
Labels: enhancement, minor

#43 fix: relock npm from inside container
  ckanext/zarr/react/package-lock.json
Labels: patch

#44 feat: make group icons on homepage show their group images as icons
  ckanext/zarr/assets/css/zarr.css
  ckanext/zarr/assets/css/zarr_palette.css
  ckanext/zarr/templates/group/snippets/group_item.html
Labels: minor

#45 185 - Fjelltopp theme leaks through on the footer
  ckanext/zarr/templates/page.html
Labels: bug, minor

#46 184 - Removes custom fields from group manage page
  ckanext/zarr/templates/group/snippets/group_form.html
Labels: bug, minor

#48 191 - Make schema metadata and groups work together
  ckanext/zarr/actions.py
  ckanext/zarr/plugin.py
Labels: enhancement, minor

#50 195 - On wide screens the dark green doesn't cover the full photo on the home page
  ckanext/zarr/assets/css/zarr.css
Labels: bug, minor

#49 192 - Make schema badges actually reflect groups
  ckanext/zarr/assets/css/zarr.css
  ckanext/zarr/assets/css/zarr_palette.css
  ckanext/zarr/helpers.py
  ckanext/zarr/plugin.py
  ckanext/zarr/templates/package/base.html
  ckanext/zarr/templates/snippets/package_item.html
Labels: enhancement, minor

#51 35 - fix:badge in dashboard dataset is not positioned in the best way
  ckanext/zarr/assets/css/zarr.css
Labels: bug, minor

#54 200 - Unable to delete draft dataset after adding it
  ckanext/zarr/templates/package/new_package_form.html
Labels: enhancement, minor

#55 196 email addresses are case sensitive
  ckanext/zarr/plugin.py
  ckanext/zarr/tests/test_authentication.py
  ckanext/zarr/tests/test_plugin.py
  setup.py
Labels: enhancement, minor
