Repository fjelltopp/ckanext-zarr, pull requests merged in 2024-09, with the labels that each got.

#25 feat: simplify schema
  ckanext/zarr/schemas/dcat_dublin.yaml
Labels: enhancement

#26 Better formatting for metadata pages
  ckanext/zarr/assets/css/zarr.css
Labels: enhancement, minor

#28 Duplicate "Licence Licence not specified" in resource read
  ckanext/zarr/assets/css/zarr.css
  ckanext/zarr/templates/package/resource_read.html
  ckanext/zarr/templates/snippets/resource_license.html
Labels: enhancement, patch

#27 fix: give webassets unique names
  ckanext/zarr/assets/webassets.yml
Labels: bug, patch

#30 ZaRR dataset read page to look like WHO-AFRO
  ckanext/zarr/assets/css/zarr.css
  ckanext/zarr/assets/css/zarr_palette.css
  ckanext/zarr/templates/package/resource_read.html
  ckanext/zarr/templates/package/snippets/additional_info.html
Labels: enhancement, minor

#37 166 - Update get_facet_items_dict with latest changes from core CKAN
  ckanext/zarr/helpers.py
Labels: bug, minor
